language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
  - composer self-update && composer --version
  - composer install

script:
  - make test-phar
  - make test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tests/_log/coverage.xml
